grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      learning_rate: 0.3
    search_param_grid:
      n_estimators :
      - 50
      - 100
   

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6